### ISSUE TITLE
Move your website to HTTPS

### ISSUE THREAD

**Issue by ayoisaiah** [HugoGiraudel/hugogiraudel.com#23]
Hi,

I'm a big fan of the new website design, it looks very good! I was wondering why you haven't moved your website to HTTPS? I know that you're not doing any sensitive stuff but still....it's something you can get for free with CloudFlare.

Keep up the great work.

**Comment by HugoGiraudel** [comment]
Hi,

Because I’m lazy and Github Pages does not provide HTTPS for custom domains out of the box. I could move it to Netlify like I did for Sass Guidelines. :)

**Comment by ayoisaiah** [comment]
I know...I just moved to HTTPS using CloudFlare and it was really easy, it shouldn't take much of your time. 

I learnt a lot about structuring a Jekyll project using your blog. Thanks.
