### ISSUE TITLE
Broken link on about page

### ISSUE THREAD

**Issue by schwardtz** [HugoGiraudel/hugogiraudel.com#34]
https://developers.google.com/experts/people/hugo-giraudel 
on 
https://github.com/HugoGiraudel/hugogiraudel.com/blob/master/about/index.md
no longer exists.

**Comment by HugoGiraudel** [comment]
It’s because I’m no longer a GDE. :(

**Comment by HugoGiraudel** [comment]
Should be fixed in a moment. Thanks!
