### ISSUE TITLE
Missing images in the "Technical documentation for everyone" blog post

### ISSUE THREAD

**Issue by d2s** [HugoGiraudel/hugogiraudel.com#38]
Images missing from the [Technical documentation for everyone](https://hugogiraudel.com/2020/01/23/technical-documentation-for-everyone/) article.

- `https://hugogiraudel.com/assets/images/technical-documentation-for-everyone/pull-request-template.png`
  - "Page Not Found"
    - "Looks like you've followed a broken link or entered a URL that doesn't exist on this site."

<img width="308" alt="2020-02-03-hugogiraudel com-missing-images2" src="https://user-images.githubusercontent.com/135053/73648394-1fb8fb00-4686-11ea-93ae-5b0d5717cb8e.PNG">

- `https://pbs.twimg.com/media/EIOFeLSWoAciNh_?format=jpg&name=large`
  - Probably a good idea to copy the image file from Twitter to the `assets/images/` directory so that it would work even when Twitter embeds fails to work.

<img width="312" alt="2020-02-03-hugogiraudel com-missing-images1" src="https://user-images.githubusercontent.com/135053/73648383-1cbe0a80-4686-11ea-8e7a-bfb30e44a703.PNG">

## Cause of the issue

- Image files disappeared in the https://github.com/HugoGiraudel/hugogiraudel.com/commit/b586ad62276039bbc19f36742177e238c74facec Git commit.
  - `assets/images/technical-documentation-for-everyone/pull-request-template.png` got removed.
- There are other blog posts that lack images after the same Git commit https://github.com/HugoGiraudel/hugogiraudel.com/commit/b586ad62276039bbc19f36742177e238c74facec
   - [Corner ribbon with trigonometry](https://hugogiraudel.com/2020/01/22/corner-ribbon-with-trigonometry/)
     - Images from `assets/images/corner-ribbon-with-trigonometry/` disappeared

**Comment by HugoGiraudel** [comment]
Hello! I can’t believe I missed that issue somehow. Thank you kindly for reporting, I just fixed the problem.
